### ISSUE TITLE
Creating a pointer at the end of rotating vector 

### ISSUE THREAD

**Issue by UnknownBrain254** [nature-of-code/noc-examples-p5.js#100]
Hey! , I'm working on a project on p5.js .I made some rotating vectors . What I want is to put somekind of pointer that can work as a pen on a tip of last rotating vector.  I try putting background() function in setup but it  doesn't work.  I'm putting the code and site of the project. Please help me with this. 
[Link](https://editor.p5js.org/himanshu2272s/sketches/qXJl4iCXl)

**Comment by shiffman** [comment]
Apologies I was never able to answer this! Unfortunately for code help a better place to ask is the Processing forum or Coding Train discord! Did you ever solve this?

https://discourse.processing.org/
https://thecodingtrain.com/discord
