### ISSUE TITLE
Add `.vscode` folder to `.gitignore`

### ISSUE THREAD

**Issue by slavisah** [nature-of-code/noc-examples-p5.js#122]
I was thinking if it's possible to add `.vscode/*` record to `.gitignore` in order to prevent `git` from taking it into account for diff.

**Comment by shiffman** [comment]
This sounds like a good idea! The only thing I can think of is would there be any VSCode settings that would be important to include in the repo? I guess not?

**Comment by slavisah** [comment]
Probably if they were not included till this point, no one is using anything specific to VSCode. If there will be a need in the future we can always add `!.vscode/settings.json` to include that one again in the repo.
