### ISSUE TITLE
[Simple SOLUTION] p5.js does not load in Processing 3.3.5 (NullPointerException)

### ISSUE THREAD

**Issue by nameszian** [nature-of-code/noc-examples-p5.js#65]
Change the following line in all index.html:
`<script language="javascript" type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.7/p5.js"></script>`
to:
`<script language="javascript" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.7/p5.js"></script>`

(Same problem at [#44](https://github.com/shiffman/The-Nature-of-Code-Examples-p5.js/issues/44))
That simple.

**Comment by shiffman** [comment]
@jasongao97 let's make sure we're updating to the latest p5 version as we go!
