### ISSUE TITLE
The nature of Code adapted to p5.js

### ISSUE THREAD

**Issue by LeonardoGentile** [nature-of-code/noc-examples-p5.js#73]
Hello, 
I'm not sure if this is the right place for this question.
Are you considering or would consider rewriting the original book so that the code used in the printed copies will be p5 instead of the original processing (java based)?

**Comment by shiffman** [comment]
Yes, that's indeed my plan for this spring! Stay tuned!

**Comment by LeonardoGentile** [comment]
Any update on this?

**Comment by shiffman** [comment]
Well, here's an update almost 4 years later, I"m back at it!!! 😬 

This time I'm really hoping it will happen (thanks to a sabbatical from teaching).
