### ISSUE TITLE
Cannot read property getDNA() of undefined

### ISSUE THREAD

**Issue by iamycee** [nature-of-code/noc-examples-p5.js#82]
I'm trying to replicate the code for SmartRockets. 
I have defined `getDNA()` function inside of the rockets.js file. 
Still, when I access it inside of the `reproduction()` method of Population class, it gives me a 'Cannot read property 'getDNA()' of undefined' error.

**Comment by shiffman** [comment]
Apologies I was never able to answer this! Unfortunately for code help a better place to ask is the Processing forum or Coding Train discord! Did you ever solve this?

https://discourse.processing.org/
https://thecodingtrain.com/discord
