### ISSUE TITLE
Typo in p5js example

### ISSUE THREAD

**Issue by lingtalfi** [nature-of-code/noc-examples-p5.js#85]
Hi, I spotted a little typo in this page:
https://github.com/nature-of-code/noc-examples-p5.js/blob/master/chp05_libraries/box2d-html5/NOC_5_01_exercise/sketch.js
on line16, we should test against the mouseIsPressed variable (i.e. the isMousePressed variable gives an error).

**Comment by joshuaalm** [comment]
Just tried this and didn't see any errors.  What sort of error were you getting?

**Comment by lingtalfi** [comment]
ReferenceError: isMousePressed is not defined

<img width="1615" alt="Screenshot 2019-07-25 at 09 15 17" src="https://user-images.githubusercontent.com/223667/61853686-cbee7d80-aebc-11e9-9e8f-6d460c041694.png">

**Comment by shiffman** [comment]
All set now with https://github.com/nature-of-code/noc-examples-p5.js/commit/15974dfdd69047eb6aac9b69222bf4054cc6053e thanks for flagging!
