### ISSUE TITLE
I can't code because of this error.  "p5 had problems creating the global...

### ISSUE THREAD

**Issue by MaanasNegi** [nature-of-code/noc-examples-p5.js#86]
Even if I do a simple program such as console.log("Hello") it is not working, the console has a message saying "p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else. ". If I removed the p5.dom script in index.html then it worked fine but I don't know what to do because most of my projects use the dom library. This error ocurred 3 days ago and I thought it was a typo from my part. I thought of that because I was learning how to add JSON files to p5 and I was getting errors and lots of them were typo so I thought that my project also had a typo but I couldn't figure anything out.

**Comment by MaanasNegi** [comment]
I changed the cdn in my index.html from something like <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js"></script>to <script src="https://cdn.JsDelivr.net/npm/p5"></script>

**Comment by RITIKA-sharma93** [comment]
I AM GETTING SAME ERROR
