### ISSUE TITLE
Animation problem

### ISSUE THREAD

**Issue by gouravbro** [nature-of-code/noc-examples-p5.js#95]
Hii coding train I am gourav.
I use official CDN of p5js from its official website and all set when i run my code on local server it works but when i host it on github then it does not works , (I am trying to build a simple game but *ellipse* is not animating). 
This is url of my repository.
https://gotii.github.io/smash/

**Comment by shiffman** [comment]
Apologies I was never able to answer this! Unfortunately for code help a better place to ask is the Processing forum or Coding Train discord! Did you ever solve this?

https://discourse.processing.org/
https://thecodingtrain.com/discord
