### ISSUE TITLE
p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.

### ISSUE THREAD

**Issue by RITIKA-sharma93** [nature-of-code/noc-examples-p5.js#96]
MY CODE IS NOT WORKING. GETTING THIS ERROR FOR EVERY CODE I RUN.

**Comment by shiffman** [comment]
Apologies I was never able to answer this! Unfortunately for code help a better place to ask is the Processing forum or Coding Train discord! Did you ever solve this?

https://discourse.processing.org/
https://thecodingtrain.com/discord
